apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: jgr-mqapi-prem
  namespace: tools
  labels:
    assembly.integration.ibm.com/tools.jgr-demo: 'true'
spec:
  license:
    accept: true
    license: L-KZVS-2G3FW4
    use: CloudPakForIntegrationNonProduction
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  replicas: 1
  version: '12.0'
  barURL:
    - >-
      https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/jgr-cp4i-mqapi-prem.bar
  configurations:
    - github-barauth
    - ace-qmgr-demo-policy
  telemetry:
    tracing:
      openTelemetry:
        enabled: true