apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-datapower-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datapower-operator-1.9.1
  publisher: IBM
  image: icr.io/cpopen/datapower-operator-catalog@sha256:ca27fcd0c507db3c0370a903caef76b1f0114e57db7eac09f2132b20fb732db2
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s