apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-3.1.0
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:15ba6c490ae23c913e4809b753dbbcb888cf30bb108892a1a384a2a88b99d031
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s